package(default_visibility = ["//visibility:public"])

filegroup(
    name = "my_company_all",
    srcs = glob([
        "README.md",
        "config/**",
        "common/**",
        "perception_adapter/**",
        "planning_plugin/**",
        "control/**",
        "tests/**",
    ]),
)
