package(default_visibility = ["//visibility:public"])

filegroup(
    name = "my_company_env_configs",
    srcs = glob([
        "environments/*.json",
        "flags/*.flags",
        "*.py",
        "*.yaml",
    ]),
)
