package(
    default_visibility = ["//visibility:public"],
)

sh_test(
    name = "command_checker_fast_test",
    srcs = ["bazel_command_checker_test.sh"],
    data = ["//scripts:apollo_base"],
)

sh_test(
    name = "find_all_package_fast_test",
    srcs = ["bazel_find_all_package_test.sh"],
    data = ["//scripts:apollo_base"],
)

sh_test(
    name = "deploy_dry_run_fast_test",
    srcs = ["bazel_deploy_dry_run_test.sh"],
    data = ["//scripts:apollo_base"],
)
